---

- hosts: sentrynet
  user: root
  any_errors_fatal: true
  gather_facts: no
  vars:
    - service: katzenmint
  roles:
    - katzenmint/install

- hosts: mixnet
  user: root
  any_errors_fatal: true
  gather_facts: no
  vars:
    - service: mix
  roles:
    - mixes/install

- hosts: providernet
  user: root
  any_errors_fatal: true
  gather_facts: no
  vars:
    - service: provider
  roles:
    - providers/install
