[Server]
  Identifier = "mix2"
  Addresses = ["0.0.0.0:30005"]
  OnlyAdvertiseAltAddresses = true
  DataDir = "/conf/data"
  IsProvider = false
  [Server.AltAddresses]
    tcp4 = ["127.0.0.1:30005"]

[Logging]
  Disable = false
  File = "katzenpost.log"
  Level = "DEBUG"

[PKI]
  [PKI.Voting]
    ChainID = "katzenmint-chain-71DRoz"
    PrimaryAddress = "tcp://172.29.1.7:26657"
    WitnessesAddresses = ["tcp://172.29.1.7:26657"]
    DatabaseName = "data-db"
    DatabaseDir = "/conf/data/kdata"
    RPCAddress = "tcp://172.29.1.7:26657"
    [PKI.Voting.TrustOptions]
      Period = 600000000000
      Height = 18
      Hash = [69, 71, 137, 124, 113, 63, 30, 78, 145, 29, 46, 113, 211, 10, 53, 239, 75, 83, 79, 124, 230, 137, 192, 127, 153, 208, 107, 45, 233, 154, 10, 216]

[Management]
  Enable = false
  Path = "/conf/data/data/management_sock"

[Debug]
  NumSphinxWorkers = 1
  NumProviderWorkers = 1
  NumKaetzchenWorkers = 3
  SchedulerExternalMemoryQueue = false
  SchedulerQueueSize = 0
  SchedulerMaxBurst = 16
  UnwrapDelay = 10
  ProviderDelay = 500
  KaetzchenDelay = 750
  SchedulerSlack = 10
  SendSlack = 50
  DecoySlack = 15000
  ConnectTimeout = 120000
  HandshakeTimeout = 600000
  ReauthInterval = 30000
  SendDecoyTraffic = false
  DisableRateLimit = true
  GenerateOnly = false
