version: "2"

services:

  auth1:
    restart: unless-stopped
    image: katzenmint/pki
    volumes:
      - ./conf/node1:/chain
    ports:
      - "127.0.0.1:21483:26657"
    networks:
      katzenmint_net:
        ipv4_address: 172.29.1.7
  auth2:
    restart: unless-stopped
    image: katzenmint/pki
    volumes:
      - ./conf/node2:/chain
    ports:
      - "127.0.0.1:21484:26657"
    networks:
      katzenmint_net:
        ipv4_address: 172.29.1.8
  auth3:
    restart: unless-stopped
    image: katzenmint/pki
    volumes:
      - ./conf/node3:/chain
    ports:
      - "127.0.0.1:21485:26657"
    networks:
      katzenmint_net:
        ipv4_address: 172.29.1.9

networks:
  katzenmint_net:
    ipam:
      driver: default
      config:
        - subnet: 172.29.0.0/16
