version: "2"

services:

  auth1:
    restart: unless-stopped
    image: katzenmint/pki
    volumes:
      - ./conf/node1:/chain
    # ports:
    #   - "127.0.0.1:21483:21483"
    networks:
      testing_net:
        ipv4_address: 172.29.1.10
  auth2:
    restart: unless-stopped
    image: katzenmint/pki
    volumes:
      - ./conf/node2:/chain
    # ports:
    #   - "127.0.0.1:22483:22483"
    networks:
      testing_net:
        ipv4_address: 172.29.1.8
  auth3:
    restart: unless-stopped
    image: katzenmint/pki
    volumes:
      - ./conf/node3:/chain
    # ports:
    #   - "127.0.0.1:23483:23483"
    networks:
      testing_net:
        ipv4_address: 172.29.1.9

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.29.0.0/16
