---

- name: Copy binary
  copy:
    src: "{{BINARY}}"
    dest: /usr/bin
    mode: 0755

- name: Copy config
  when: item <= N and ansible_hostname == 'cyclotron-sentrynet-node' ~ item
  copy:
    src: "{{CONFIGDIR}}/node{{item}}/"
    dest: "/home/{{service}}/.{{service}}/"
    owner: "{{service}}"
    group: "{{service}}"
  loop: [ 0, 1, 2 ]

