[Server]
  Identifier = "provider1"
  Addresses = ["0.0.0.0:30001"]
  OnlyAdvertiseAltAddresses = true
  DataDir = "/conf/data"
  IsProvider = true
  [Server.AltAddresses]
    tcp4 = ["127.0.0.1:30001"]

[Logging]
  Disable = false
  File = "katzenpost.log"
  Level = "DEBUG"

[Provider]
  EnableUserRegistrationHTTP = true
  UserRegistrationHTTPAddresses = ["0.0.0.0:40001"]
  AdvertiseUserRegistrationHTTPAddresses = ["http://127.0.0.1:40001"]
  BinaryRecipients = false
  CaseSensitiveRecipients = false
  RecipientDelimiter = ""
  [Provider.UserDB]
    Backend = "bolt"
    [Provider.UserDB.Bolt]
      UserDB = "/conf/data/users.db"
  [Provider.SpoolDB]
    Backend = "bolt"
    [Provider.SpoolDB.Bolt]
      SpoolDB = "/conf/data/spool.db"

  [[Provider.Kaetzchen]]
    Capability = "loop"
    Endpoint = "+loop"
    Disable = false

  [[Provider.CBORPluginKaetzchen]]
    Capability = "echo"
    Endpoint = "+echo"
    Command = "/go/bin/echo_server"
    MaxConcurrency = 1
    Disable = false
    [Provider.CBORPluginKaetzchen.Config]
      log_dir = "/conf/data"
      log_level = "DEBUG"

  [[Provider.CBORPluginKaetzchen]]
    Capability = "panda"
    Endpoint = "+panda"
    Command = "/go/bin/panda_server"
    MaxConcurrency = 1
    Disable = false
    [Provider.CBORPluginKaetzchen.Config]
      fileStore = "/conf/data/panda.storage"
      log_dir = "/conf/data"
      log_level = "DEBUG"

  [[Provider.CBORPluginKaetzchen]]
    Capability = "spool"
    Endpoint = "+spool"
    Command = "/go/bin/memspool"
    MaxConcurrency = 1
    Disable = false
    [Provider.CBORPluginKaetzchen.Config]
      data_store = "/conf/data/memspool.storage"
      log_dir = "/conf/data"

  [[Provider.CBORPluginKaetzchen]]
    Capability = "gor"
    Endpoint = "+gor"
    Command = "/go/bin/Meson"
    MaxConcurrency = 1
    Disable = false
    [Provider.CBORPluginKaetzchen.Config]
      f = "/conf/data/currency.toml"
      log_dir = "/conf/data"
      log_level = "DEBUG"

[PKI]
  [PKI.Voting]
    ChainID = "katzenmint-chain-71DRoz"
    PrimaryAddress = "tcp://172.29.1.7:26657"
    WitnessesAddresses = ["tcp://172.29.1.7:26657"]
    DatabaseName = "data-db"
    DatabaseDir = "/Users/laiguancheng/Desktop/projects/hashcloak/genconfig/output/data"
    RPCAddress = "tcp://172.29.1.7:26657"
    [PKI.Voting.TrustOptions]
      Period = 600000000000
      Height = 13
      Hash = [40, 152, 216, 225, 246, 117, 67, 139, 60, 167, 110, 22, 156, 186, 49, 35, 229, 70, 29, 171, 231, 62, 42, 242, 136, 32, 3, 111, 120, 229, 33, 194]

[Management]
  Enable = true
  Path = "/conf/data/management_sock"

[Debug]
  NumSphinxWorkers = 1
  NumProviderWorkers = 1
  NumKaetzchenWorkers = 3
  SchedulerExternalMemoryQueue = false
  SchedulerQueueSize = 0
  SchedulerMaxBurst = 16
  UnwrapDelay = 10
  ProviderDelay = 500
  KaetzchenDelay = 750
  SchedulerSlack = 10
  SendSlack = 50
  DecoySlack = 15000
  ConnectTimeout = 120000
  HandshakeTimeout = 600000
  ReauthInterval = 30000
  SendDecoyTraffic = false
  DisableRateLimit = true
  GenerateOnly = false
